export const LICENSE_PUBLIC_KEY = `-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxU/NyFAovGpscbDVc6cR
1aXKQYinLLWPJA+Jw9FJlqNdpbsTeW/MWVbQCUHmZLO12Qdbzwej28lY0JnYXqBh
b5Kg6kNEY71T5hnab7pQ3QGigYSCUHwwytKuq/w7hwTxyOC5YrYj/A0HTroLBSgp
vsuhp/7r/tmcUagrm3IfdeSwpIVTGhwFJg9MaoWreIjLuek7YY3riVqgrAp2dU/0
yXqxHYp8wSwLlOQIC97QCvRmYQxH17fS7F2Nsy1JOmCmISvlsnftIFfgtcRuXQ/i
pxRHautzAgdlc2OSJYFlKu91uK2fBDvQiFMvE99g+lSP9zpvfKY08RHcYoTTnPUs
wQIDAQAB
-----END PUBLIC KEY-----`;
