UPDATE "User" SET "role" = 'ROLE_ADMIN' WHERE UPPER("role") = 'ADMIN';
UPDATE "User" SET "role" = 'ROLE_CASHIER' WHERE UPPER("role") IN ('OPERATOR', 'CASHIER');
ALTER TABLE "User" ALTER COLUMN "role" SET DEFAULT 'ROLE_CASHIER';
